### ISSUE TITLE
Runtime exception while running most.out.sumocfg

### ISSUE THREAD

**Issue by tarapt** [lcodeca/MoSTScenario#3] opened 2019-06-01 11:30 UTC
SUMO Version: 1.2
OS: Ubuntu 16.04
Python Version: 3.5.2

![image](https://user-images.githubusercontent.com/10519897/58747915-556e6a00-848f-11e9-9539-5ccbd6f43b5a.png)

**Comment by lcodeca** [comment] 2019-06-02 13:34
You are using SUMO with debug enabled and there you have an assertion triggered. 
Can you please use SUMO without the debug enabled and send me the log files? (not an image)
Thank you.

**Comment by tarapt** [comment] 2019-06-08 11:52
Sorry for the late response, I was busy with another project. I wanted to run SUMO without debug enabled, but I couldn't find any info on doing that. I tried sumo --help, but couldn't find the debug option. So, I ran the most.out.sumocfg file again. The output to the terminal wasn't getting logged to any file automatically, so I manually copied it into a file.

[most.sim.log](https://github.com/lcodeca/MoSTScenario/files/3268478/most.sim.log)
[terminal_output.txt](https://github.com/lcodeca/MoSTScenario/files/3268479/terminal_output.txt)

**Comment by lcodeca** [comment] 2019-06-10 07:16
I cannot reproduce your problem, I don't know how to help you.
When you type sumo in your terminal, what is the output? What does it say in the "Build features"?
Your problem is generated by an assertion that should be triggered only if you are using the debug version of sumo as far as I know. Have you tried to ask the SUMO community?

**Comment by tarapt** [comment] 2019-06-10 11:25
Here's my sumo output - 
`Eclipse SUMO Version 1.2.0
 Build features: Linux-4.4.0-146-generic x86_64 GNU 5.4.0 None Proj GUI GDAL GL2PS
 Copyright (C) 2001-2019 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
`
It's ok if you can't find the problem. I am new to sumo and traci, so I just wanted to go through some existing projects to get familiar with the framework and api. After going through the sumo wiki I was able to implement my requirements. So, its alright even if you close this issue.

**Comment by lcodeca** [comment] 2019-06-10 12:59
I suppose you compiled it yourself? The `None` in the building features should be `Release` or `Debug`.
I suppose that with `None` it defaults on `Debug`, hence your triggered assertion. This is the only explanation that I can think of.
If you build it with cmake, you need to add `--config Release` to your command line.
I hope this helps.

**Comment by tarapt** [comment] 2019-06-10 16:44
No, that was not the case, I didn't compile from source. I installed it through apt by following the instructions from [Sumo Wiki](https://sumo.dlr.de/wiki/Installing). 
`sudo apt-get install sumo sumo-tools sumo-doc`
But, at least the issue is clear, I should get `Release` instead of `None` in the version info. This should help me if some similar error occurs in future. Thanks for helping.

**Comment by lcodeca** [comment] 2019-06-10 17:27
Then I don't know how to help you, sorry.
If I were you, I would ask directly to the sumo mailing list. I cannot contact them for you because I cannot reproduce your issue. Given that you installed through `apt-get`, it's possible that my supposition is wrong. I have no idea why an official release would have assertions enabled.
I'm going to close the issue, but if you need help with MoST, do not hesitate to contact me directly.

**Closed as completed by lcodeca** 2019-06-10 17:27 UTC
